powershell -Command "(New-Object Net.WebClient).DownloadFile('https://github.com/Isamuishi/funnycat/releases/download/balls/catjam-cat-dancing.gif', 'caht.gif')"
powershell -Command "Invoke-WebRequest https://github.com/Isamuishi/funnycat/releases/download/balls/catjam-cat-dancing.gif -OutFile caht.gif"

@echo off
cd "Downloads"
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
start caht.gif
